[build]
  command = "npm run build"
  publish = "dist"


[[plugins]]
  package = "@netlify/plugin-local-install-core"

# Config for the Netlify Build Plugin: netlify-plugin-trello-lists
[[plugins]]
  package = "netlify-plugin-trello-lists"

  [plugins.inputs]

    # The URL of a publicly visible Trello board
    trelloBoardUrl = "https://trello.com/b/twPXW2W1/netlify-plugin-trello-list-info"

    # Location of the JSON data file to be generated
    dataFilePath = "src/_data/trello.json"

    # If the plugin fails, should it do so quietly or cancel the build?
    # "failBuild" | "failPlugin"
    fail = "failBuild"


